### ISSUE TITLE
Turn into react npm package with a nice wrapper component??

### ISSUE THREAD

**Issue by The-Code-Monkey** [AwesomeWebProjects/React-Player#37]
would it be possible to change this into a nice wrapped component so we can use it like 

`import Audio from 'react-audio-visualizer'`

**Comment by danielbarion** [comment]
Hey @The-Code-Monkey !

Yeah, it's possible, but for now, I'm focused to improve some items (you can read more in the board)

**Comment by danielbarion** [comment]
@The-Code-Monkey just a little feedback, i'm so busy now, but i'll take a look in this issue when i back code into player project okay.

**Comment by danielbarion** [comment]
I'm back, I liked your suggestion, thanks!

**Comment by danielbarion** [comment]
@The-Code-Monkey I'm working on It.

**Comment by danielbarion** [comment]
https://github.com/AwesomeWebProjects/React-Player/releases/tag/v1.0.0
